# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

from datetime import datetime
from enum import Enum
from typing import (
    Annotated,
    Any,
    AsyncIterator,
    Dict,
    List,
    Literal,
    Optional,
    Protocol,
    Union,
    runtime_checkable,
)

from pydantic import BaseModel, ConfigDict, Field

from llama_stack.apis.common.content_types import URL, ContentDelta, InterleavedContent
from llama_stack.apis.inference import (
    CompletionMessage,
    ResponseFormat,
    SamplingParams,
    ToolChoice,
    ToolConfig,
    ToolResponse,
    ToolResponseMessage,
    UserMessage,
)
from llama_stack.apis.safety import SafetyViolation
from llama_stack.apis.tools import ToolDef
from llama_models.datatypes import ToolCall, ToolPromptFormat, StopReason, BuiltinTool
from llama_stack.providers.utils.telemetry.trace_protocol import trace_protocol
from llama_stack.schema_utils import json_schema_type, register_schema, webmethod


class Attachment(BaseModel):
    """An attachment to a message in an agent interaction.
    
    Attributes:
        content: The content of the attachment, which can be either inline content or a URL.
        mime_type: The MIME type of the attachment content.
    """
    content: Any  # Union[InterleavedContent, URL]
    mime_type: str


class Document(BaseModel):
    """A document that can be provided to an agent.
    
    Attributes:
        content: The content of the document, which can be either inline content or a URL.
        mime_type: The MIME type of the document content.
    """
    content: Any  # Union[InterleavedContent, URL]
    mime_type: str


class StepCommon(BaseModel):
    """Common attributes for all step types in an agent interaction.
    
    Attributes:
        turn_id: Unique identifier for the turn this step belongs to.
        step_id: Unique identifier for this step.
        started_at: Timestamp when the step started, or None if not started.
        completed_at: Timestamp when the step completed, or None if not completed.
    """
    turn_id: str
    step_id: str
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


class StepType(Enum):
    """Types of steps that can occur during an agent interaction.
    
    Attributes:
        inference: A step where the agent generates a response.
        tool_execution: A step where the agent executes a tool.
        shield_call: A step where a safety shield is called.
        memory_retrieval: A step where the agent retrieves information from memory.
    """
    inference = "inference"
    tool_execution = "tool_execution"
    shield_call = "shield_call"
    memory_retrieval = "memory_retrieval"


@json_schema_type
class InferenceStep(StepCommon):
    """A step where the agent generates a response using an inference model.
    
    Attributes:
        step_type: The type of step, always "inference" for this class.
        model_response: The response generated by the model.
    """
    model_config = ConfigDict(protected_namespaces=())

    step_type: str = StepType.inference.value
    model_response: CompletionMessage


@json_schema_type
class ToolExecutionStep(StepCommon):
    """A step where the agent executes one or more tools.
    
    Attributes:
        step_type: The type of step, always "tool_execution" for this class.
        tool_calls: List of tool calls made by the agent.
        tool_responses: List of responses from the executed tools.
    """
    step_type: str = StepType.tool_execution.value
    tool_calls: List[ToolCall]
    tool_responses: List[ToolResponse]


@json_schema_type
class ShieldCallStep(StepCommon):
    """A step where a safety shield is called to check for violations.
    
    Attributes:
        step_type: The type of step, always "shield_call" for this class.
        violation: The safety violation detected, if any.
    """
    step_type: str = StepType.shield_call.value
    violation: Optional[SafetyViolation]


@json_schema_type
class MemoryRetrievalStep(StepCommon):
    """A step where the agent retrieves information from memory.
    
    Attributes:
        step_type: The type of step, always "memory_retrieval" for this class.
        vector_db_ids: Identifier for the vector database used for retrieval.
        inserted_context: The context retrieved from memory.
    """
    step_type: str = StepType.memory_retrieval.value
    vector_db_ids: str
    inserted_context: Any  # InterleavedContent


Step = Annotated[
    Union[
        InferenceStep,
        ToolExecutionStep,
        ShieldCallStep,
        MemoryRetrievalStep,
    ],
    Field(discriminator="step_type"),
]


@json_schema_type
class Turn(BaseModel):
    """A single turn in an interaction with an Agentic System."""

    turn_id: str
    session_id: str
    input_messages: List[
        Union[
            UserMessage,
            ToolResponseMessage,
        ]
    ]
    steps: List[Step]
    output_message: CompletionMessage
    output_attachments: Optional[List[Attachment]] = Field(default_factory=list)

    started_at: datetime
    completed_at: Optional[datetime] = None


@json_schema_type
class Session(BaseModel):
    """A single session of an interaction with an Agentic System."""

    session_id: str
    session_name: str
    turns: List[Turn]
    started_at: datetime


class AgentToolGroupWithArgs(BaseModel):
    name: str
    args: Dict[str, Any]


AgentToolGroup = register_schema(
    Union[
        str,
        AgentToolGroupWithArgs,
    ],
    name="AgentTool",
)


class AgentConfigCommon(BaseModel):
    """Common configuration parameters for agents.
    
    This class defines configuration parameters that are common to both
    the initial agent configuration and per-turn overrides.
    
    Attributes:
        sampling_params: Parameters for controlling the sampling behavior of the model.
        input_shields: List of input safety shields to apply.
        output_shields: List of output safety shields to apply.
        toolgroups: List of tool groups available to the agent.
        client_tools: List of client-side tools available to the agent.
        tool_choice: How the agent should choose tools (deprecated, use tool_config).
        tool_prompt_format: Format for tool prompts (deprecated, use tool_config).
        tool_config: Configuration for tool usage.
        max_infer_iters: Maximum number of inference iterations.
    """
    sampling_params: Optional[SamplingParams] = SamplingParams()

    input_shields: Optional[List[str]] = Field(default_factory=list)
    output_shields: Optional[List[str]] = Field(default_factory=list)
    toolgroups: Optional[List[Any]] = Field(default_factory=list)  # List[AgentToolGroup]
    client_tools: Optional[List[ToolDef]] = Field(default_factory=list)
    tool_choice: Optional[ToolChoice] = Field(default=None, deprecated="use tool_config instead")
    tool_prompt_format: Optional[ToolPromptFormat] = Field(default=None, deprecated="use tool_config instead")
    tool_config: Optional[ToolConfig] = Field(default=None)

    max_infer_iters: Optional[int] = 10

    def model_post_init(self, __context):
        """Post-initialization validation and setup.
        
        This method is called after the model is initialized to validate
        the configuration and set up the tool_config if needed.
        
        Args:
            __context: The initialization context.
            
        Raises:
            ValueError: If deprecated parameters are used inconsistently with tool_config.
        """
        if self.tool_config:
            if self.tool_choice and self.tool_config.tool_choice != self.tool_choice:
                raise ValueError("tool_choice is deprecated. Use tool_choice in tool_config instead.")
            if self.tool_prompt_format and self.tool_config.tool_prompt_format != self.tool_prompt_format:
                raise ValueError("tool_prompt_format is deprecated. Use tool_prompt_format in tool_config instead.")
        else:
            params = {}
            if self.tool_choice:
                params["tool_choice"] = self.tool_choice
            if self.tool_prompt_format:
                params["tool_prompt_format"] = self.tool_prompt_format
            self.tool_config = ToolConfig(**params)


@json_schema_type
class AgentConfig(AgentConfigCommon):
    """Configuration for creating an agent.
    
    This class extends AgentConfigCommon with parameters specific to
    the initial agent configuration.
    
    Attributes:
        model: The model to use for the agent.
        instructions: Instructions for the agent.
        enable_session_persistence: Whether to persist the session state.
        response_format: Format for the agent's responses.
    """
    model: str
    instructions: str
    enable_session_persistence: Optional[bool] = False
    response_format: Optional[Any] = None  # ResponseFormat


class AgentConfigOverridablePerTurn(AgentConfigCommon):
    """Configuration parameters that can be overridden per turn.
    
    This class extends AgentConfigCommon with parameters that can be
    overridden on a per-turn basis.
    
    Attributes:
        instructions: Optional instructions that override the agent's default instructions.
    """
    instructions: Optional[str] = None


class AgentTurnResponseEventType(Enum):
    """Types of events that can occur during an agent turn.
    
    Attributes:
        step_start: Event indicating a step has started.
        step_complete: Event indicating a step has completed.
        step_progress: Event indicating progress within a step.
        turn_start: Event indicating a turn has started.
        turn_complete: Event indicating a turn has completed.
        turn_awaiting_input: Event indicating a turn is awaiting input.
    """
    step_start = "step_start"
    step_complete = "step_complete"
    step_progress = "step_progress"

    turn_start = "turn_start"
    turn_complete = "turn_complete"
    turn_awaiting_input = "turn_awaiting_input"


@json_schema_type
class AgentTurnResponseStepStartPayload(BaseModel):
    event_type: str = AgentTurnResponseEventType.step_start.value
    step_type: StepType
    step_id: str
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


@json_schema_type
class AgentTurnResponseStepCompletePayload(BaseModel):
    event_type: str = AgentTurnResponseEventType.step_complete.value
    step_type: StepType
    step_id: str
    step_details: Step


@json_schema_type
class AgentTurnResponseStepProgressPayload(BaseModel):
    model_config = ConfigDict(protected_namespaces=())

    event_type: str = AgentTurnResponseEventType.step_progress.value
    step_type: StepType
    step_id: str

    delta: Any  # ContentDelta


@json_schema_type
class AgentTurnResponseTurnStartPayload(BaseModel):
    event_type: str = AgentTurnResponseEventType.turn_start.value
    turn_id: str


@json_schema_type
class AgentTurnResponseTurnCompletePayload(BaseModel):
    event_type: str = AgentTurnResponseEventType.turn_complete.value
    turn: Turn


@json_schema_type
class AgentTurnResponseTurnAwaitingInputPayload(BaseModel):
    event_type: str = AgentTurnResponseEventType.turn_awaiting_input.value
    turn: Turn


AgentTurnResponseEventPayload = register_schema(
    Annotated[
        Union[
            AgentTurnResponseStepStartPayload,
            AgentTurnResponseStepProgressPayload,
            AgentTurnResponseStepCompletePayload,
            AgentTurnResponseTurnStartPayload,
            AgentTurnResponseTurnCompletePayload,
            AgentTurnResponseTurnAwaitingInputPayload,
        ],
        Field(discriminator="event_type"),
    ],
    name="AgentTurnResponseEventPayload",
)


@json_schema_type
class AgentTurnResponseEvent(BaseModel):
    payload: Any  # AgentTurnResponseEventPayload


@json_schema_type
class AgentCreateResponse(BaseModel):
    agent_id: str


@json_schema_type
class AgentSessionCreateResponse(BaseModel):
    session_id: str


@json_schema_type
class AgentTurnCreateRequest(AgentConfigOverridablePerTurn):
    agent_id: str
    session_id: str

    # TODO: figure out how we can simplify this and make why
    # ToolResponseMessage needs to be here (it is function call
    # execution from outside the system)
    messages: List[
        Union[
            UserMessage,
            ToolResponseMessage,
        ]
    ]

    documents: Optional[List[Document]] = None
    toolgroups: Optional[List[Any]] = None  # List[AgentToolGroup]

    stream: Optional[bool] = False
    tool_config: Optional[ToolConfig] = None

    # TODO (xiyan): temporary flag, will remove for 0.1.5
    allow_turn_resume: Optional[bool] = False


@json_schema_type
class AgentTurnResumeRequest(BaseModel):
    agent_id: str
    session_id: str
    turn_id: str
    tool_responses: List[ToolResponseMessage]
    stream: Optional[bool] = False


@json_schema_type
class AgentTurnResponseStreamChunk(BaseModel):
    """streamed agent turn completion response."""

    event: AgentTurnResponseEvent


@json_schema_type
class AgentStepResponse(BaseModel):
    step: Step


@runtime_checkable
@trace_protocol
class Agents(Protocol):
    """Agents API for creating and interacting with agentic systems.

    This protocol defines the interface for creating and interacting with agents,
    which are AI systems that can perform tasks, use tools, and maintain state
    across multiple interactions.

    Main functionalities provided by this API:
    - Create agents with specific instructions and ability to use tools.
    - Interactions with agents are grouped into sessions ("threads"), and each interaction is called a "turn".
    - Agents can be provided with various tools (see the ToolGroups and ToolRuntime APIs for more details).
    - Agents can be provided with various shields (see the Safety API for more details).
    - Agents can also use Memory to retrieve information from knowledge bases. See the RAG Tool and Vector IO APIs for more details.
    """
    # The following methods are protocol definitions and not actual implementations

    # @webmethod(route="/agents", method="POST")
    async def create_agent(
        self,
        agent_config: AgentConfig,
    ) -> AgentCreateResponse:
        """Create a new agent with the specified configuration.
        
        Args:
            agent_config: Configuration for the agent, including model, instructions,
                          and available tools.
                          
        Returns:
            A response containing the ID of the created agent.
        """
        ...

    # @webmethod(route="/agents/{agent_id}/session/{session_id}/turn", method="POST")
    async def create_agent_turn(
        self,
        agent_id: str,
        session_id: str,
        messages: List[
            Union[
                UserMessage,
                ToolResponseMessage,
            ]
        ],
        stream: Optional[bool] = False,
        documents: Optional[List[Document]] = None,
        toolgroups: Optional[List[Any]] = None,  # List[AgentToolGroup]
        tool_config: Optional[ToolConfig] = None,
        allow_turn_resume: Optional[bool] = False,
    ) -> Union[Turn, AsyncIterator[AgentTurnResponseStreamChunk]]:
        """Create a new turn in an agent session.
        
        A turn represents a single interaction with the agent, where the agent
        receives messages, processes them, and generates a response. The agent
        may use tools, retrieve information from memory, and apply safety shields
        during this process.
        
        Args:
            agent_id: The ID of the agent to interact with.
            session_id: The ID of the session to create the turn in.
            messages: The messages to send to the agent.
            stream: Whether to stream the response or return it all at once.
            documents: Optional documents to provide to the agent.
            toolgroups: Optional tool groups to make available for this turn.
            tool_config: Optional tool configuration for this turn.
            allow_turn_resume: Whether to allow resuming this turn later.
            
        Returns:
            If stream is False, returns a Turn object containing the complete
            interaction. If stream is True, returns an AsyncIterator that yields
            AgentTurnResponseStreamChunk objects as the turn progresses.
        """
        ...

    # Protocol method for resuming an agent turn
    # route="/agents/{agent_id}/session/{session_id}/turn/{turn_id}/resume", method="POST"
    async def resume_agent_turn(
        self,
        agent_id: str,
        session_id: str,
        turn_id: str,
        tool_responses: List[ToolResponseMessage],
        stream: Optional[bool] = False,
    ) -> Union[Turn, AsyncIterator[AgentTurnResponseStreamChunk]]:
        """Resume an agent turn with executed tool call responses.

        When a Turn has the status `awaiting_input` due to pending input from client side tool calls, this endpoint can be used to submit the outputs from the tool calls once they are ready.

        :param agent_id: The ID of the agent to resume.
        :param session_id: The ID of the session to resume.
        :param turn_id: The ID of the turn to resume.
        :param tool_responses: The tool call responses to resume the turn with.
        :param stream: Whether to stream the response.
        :returns: A Turn object if stream is False, otherwise an AsyncIterator of AgentTurnResponseStreamChunk objects.
        """
        ...

    # Protocol method for getting an agent turn
    # route="/agents/{agent_id}/session/{session_id}/turn/{turn_id}", method="GET"
    async def get_agents_turn(
        self,
        agent_id: str,
        session_id: str,
        turn_id: str,
    ) -> Turn:
        """Get information about a specific turn in an agent session.
        
        Args:
            agent_id: The ID of the agent.
            session_id: The ID of the session.
            turn_id: The ID of the turn to get.
            
        Returns:
            A Turn object containing information about the turn.
        """
        ...

    # Protocol method for getting an agent step
    # route="/agents/{agent_id}/session/{session_id}/turn/{turn_id}/step/{step_id}", method="GET"
    async def get_agents_step(
        self,
        agent_id: str,
        session_id: str,
        turn_id: str,
        step_id: str,
    ) -> AgentStepResponse:
        """Get information about a specific step in an agent turn.
        
        Args:
            agent_id: The ID of the agent.
            session_id: The ID of the session.
            turn_id: The ID of the turn.
            step_id: The ID of the step to get.
            
        Returns:
            An AgentStepResponse object containing information about the step.
        """
        ...

    # @webmethod(route="/agents/{agent_id}/session", method="POST")
    async def create_agent_session(
        self,
        agent_id: str,
        session_name: str,
    ) -> AgentSessionCreateResponse:
        """Create a new session for an agent.
        
        A session represents a conversation thread with an agent, allowing
        for maintaining context across multiple turns.
        
        Args:
            agent_id: The ID of the agent to create a session for.
            session_name: A name for the session.
            
        Returns:
            A response containing the ID of the created session.
        """
        ...

    # @webmethod(route="/agents/{agent_id}/session/{session_id}", method="GET")
    async def get_agents_session(
        self,
        session_id: str,
        agent_id: str,
        turn_ids: Optional[List[str]] = None,
    ) -> Session:
        """Get information about an agent session.
        
        Args:
            session_id: The ID of the session to get.
            agent_id: The ID of the agent the session belongs to.
            turn_ids: Optional list of turn IDs to include in the response.
                      If not provided, all turns in the session are included.
            
        Returns:
            A Session object containing information about the session.
        """
        ...

    # @webmethod(route="/agents/{agent_id}/session/{session_id}", method="DELETE")
    async def delete_agents_session(
        self,
        session_id: str,
        agent_id: str,
    ) -> None:
        """Delete an agent session.
        
        Args:
            session_id: The ID of the session to delete.
            agent_id: The ID of the agent the session belongs to.
            
        Returns:
            None
        """
        ...

    # @webmethod(route="/agents/{agent_id}", method="DELETE")
    async def delete_agent(
        self,
        agent_id: str,
    ) -> None:
        """Delete an agent.
        
        Args:
            agent_id: The ID of the agent to delete.
            
        Returns:
            None
        """
        ...
