# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

from __future__ import annotations

from datetime import datetime
from enum import Enum

from typing import (
    Annotated,
    Any,
    AsyncIterator,
    Dict,
    List,
    Literal,
    Optional,
    Protocol,
    Union,
    runtime_checkable,
)

from pydantic import BaseModel, ConfigDict, Field

from llama_stack.apis.common.content_types import InterleavedContent
from llama_stack.apis.inference import (
    CompletionMessage,
    SamplingParams,
    ToolChoice,
    ToolConfig,
    ToolResponse,
    ToolResponseMessage,
    UserMessage,
)
from llama_models.datatypes import ToolCall, ToolPromptFormat
from llama_stack.apis.safety import SafetyViolation
from llama_stack.apis.tools import ToolDef
from llama_stack.providers.utils.telemetry.trace_protocol import trace_protocol
from llama_stack.schema_utils import json_schema_type, register_schema, webmethod  # type: ignore


class Attachment(BaseModel):
    """An attachment that can be included in agent responses.
    
    Attachments can contain either interleaved content (text, images, etc.) or a URL
    pointing to external content.
    
    Attributes:
        content: The content of the attachment, either interleaved or a URL
        mime_type: The MIME type of the attachment content
    """
    content: Any  # Union[InterleavedContent, URL]
    mime_type: str


class Document(BaseModel):
    """A document that can be provided to an agent for processing.
    
    Documents can contain either interleaved content (text, images, etc.) or a URL
    pointing to external content.
    
    Attributes:
        content: The content of the document, either interleaved or a URL
        mime_type: The MIME type of the document content
    """
    content: Any  # Union[InterleavedContent, URL]
    mime_type: str


class StepCommon(BaseModel):
    """Common attributes for all step types in an agent interaction.
    
    Steps represent individual actions taken by an agent during a turn, such as
    inference, tool execution, shield calls, or memory retrieval.
    
    Attributes:
        turn_id: Unique identifier for the turn this step belongs to
        step_id: Unique identifier for this step
        started_at: Timestamp when the step started
        completed_at: Timestamp when the step completed
    """
    turn_id: str
    step_id: str
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


class StepType(Enum):
    """Enumeration of different types of steps in an agent interaction.
    
    Each step type represents a different kind of action that an agent can take
    during a turn.
    
    Attributes:
        inference: Step where the agent generates a response using the model
        tool_execution: Step where the agent executes a tool
        shield_call: Step where a safety shield is called
        memory_retrieval: Step where the agent retrieves information from memory
    """
    inference = "inference"
    tool_execution = "tool_execution"
    shield_call = "shield_call"
    memory_retrieval = "memory_retrieval"


@json_schema_type
class InferenceStep(StepCommon):
    """Step representing an inference operation by the agent.
    
    This step occurs when the agent generates a response using the model.
    
    Attributes:
        step_type: The type of step, always "inference" for this class
        model_response: The completion message generated by the model
    """
    model_config = ConfigDict(protected_namespaces=())

    step_type: Literal["inference"] = StepType.inference.value
    model_response: CompletionMessage


@json_schema_type
class ToolExecutionStep(StepCommon):
    """Step representing a tool execution operation by the agent.
    
    This step occurs when the agent executes one or more tools to perform
    specific actions or retrieve information.
    
    Attributes:
        step_type: The type of step, always "tool_execution" for this class
        tool_calls: List of tool calls made by the agent
        tool_responses: List of responses from the executed tools
    """
    step_type: Literal["tool_execution"] = StepType.tool_execution.value
    tool_calls: List[ToolCall]
    tool_responses: List[ToolResponse]


@json_schema_type
class ShieldCallStep(StepCommon):
    """Step representing a safety shield call by the agent.
    
    This step occurs when a safety shield is called to check for potential
    safety violations in agent inputs or outputs.
    
    Attributes:
        step_type: The type of step, always "shield_call" for this class
        violation: Optional safety violation detected by the shield, None if no violation
    """
    step_type: Literal["shield_call"] = StepType.shield_call.value
    violation: Optional[SafetyViolation]


@json_schema_type
class MemoryRetrievalStep(StepCommon):
    """Step representing a memory retrieval operation by the agent.
    
    This step occurs when the agent retrieves information from a vector database
    or other memory storage.
    
    Attributes:
        step_type: The type of step, always "memory_retrieval" for this class
        vector_db_ids: Identifier for the vector database used
        inserted_context: The retrieved context information
    """
    step_type: Literal["memory_retrieval"] = StepType.memory_retrieval.value
    vector_db_ids: str
    inserted_context: Any  # InterleavedContent


Step = Annotated[
    Union[
        InferenceStep,
        ToolExecutionStep,
        ShieldCallStep,
        MemoryRetrievalStep,
    ],
    Field(discriminator="step_type"),
]


@json_schema_type
class Turn(BaseModel):
    """A single turn in an interaction with an Agentic System.
    
    A turn represents a complete interaction cycle with an agent, including the input
    messages, the steps taken by the agent, and the final output message.
    
    Attributes:
        turn_id: Unique identifier for this turn
        session_id: Identifier for the session this turn belongs to
        input_messages: List of input messages for this turn
        steps: List of steps taken by the agent during this turn
        output_message: The final completion message generated by the agent
        output_attachments: Optional list of attachments included in the response
        started_at: Timestamp when the turn started
        completed_at: Timestamp when the turn completed, None if still in progress
    """

    turn_id: str
    session_id: str
    input_messages: List[
        Union[
            UserMessage,
            ToolResponseMessage,
        ]
    ]
    steps: List[Step]
    output_message: CompletionMessage
    output_attachments: Optional[List[Attachment]] = Field(default_factory=list)

    started_at: datetime
    completed_at: Optional[datetime] = None


@json_schema_type
class Session(BaseModel):
    """A single session of an interaction with an Agentic System.
    
    A session represents a continuous conversation with an agent, consisting of
    multiple turns. Sessions maintain context across turns, allowing for more
    coherent and contextual interactions.
    
    Attributes:
        session_id: Unique identifier for this session
        session_name: Human-readable name for the session
        turns: List of turns that have occurred in this session
        started_at: Timestamp when the session started
    """

    session_id: str
    session_name: str
    turns: List[Turn]
    started_at: datetime


class AgentToolGroupWithArgs(BaseModel):
    """A tool group with arguments for agent configuration.
    
    This class represents a tool group that can be provided to an agent,
    along with specific arguments for that tool group.
    
    Attributes:
        name: The name of the tool group
        args: Dictionary of arguments for the tool group
    """
    name: str
    args: Dict[str, Any]


AgentToolGroup = register_schema(
    Union[
        str,
        AgentToolGroupWithArgs,
    ],
    name="AgentTool",
)


class AgentConfigCommon(BaseModel):
    """Common configuration parameters for agents.
    
    This class defines the common configuration parameters that are shared
    between different agent configuration classes.
    
    Attributes:
        sampling_params: Parameters for controlling the sampling behavior of the model
        input_shields: List of input safety shields to apply
        output_shields: List of output safety shields to apply
        toolgroups: List of tool groups available to the agent
        client_tools: List of client-side tools available to the agent
        tool_choice: Tool choice configuration (deprecated, use tool_config instead)
        tool_prompt_format: Tool prompt format configuration (deprecated, use tool_config instead)
        tool_config: Consolidated tool configuration
        max_infer_iters: Maximum number of inference iterations
    """
    sampling_params: Optional[SamplingParams] = SamplingParams()

    input_shields: Optional[List[str]] = Field(default_factory=list)
    output_shields: Optional[List[str]] = Field(default_factory=list)
    toolgroups: Optional[List[Any]] = Field(default_factory=list)  # List[AgentToolGroup]
    client_tools: Optional[List[ToolDef]] = Field(default_factory=list)
    tool_choice: Optional[ToolChoice] = Field(default=None, deprecated="use tool_config instead")
    tool_prompt_format: Optional[ToolPromptFormat] = Field(default=None, deprecated="use tool_config instead")
    tool_config: Optional[ToolConfig] = Field(default=None)

    max_infer_iters: Optional[int] = 10

    def model_post_init(self, __context):
        """Post-initialization validation and setup.
        
        This method is called after the model is initialized to validate
        configuration parameters and set up defaults.
        
        Args:
            __context: Initialization context (not used)
            
        Raises:
            ValueError: If deprecated parameters are used inconsistently with tool_config
        """
        if self.tool_config:
            if self.tool_choice and self.tool_config.tool_choice != self.tool_choice:
                raise ValueError("tool_choice is deprecated. Use tool_choice in tool_config instead.")
            if self.tool_prompt_format and self.tool_config.tool_prompt_format != self.tool_prompt_format:
                raise ValueError("tool_prompt_format is deprecated. Use tool_prompt_format in tool_config instead.")
        else:
            params = {}
            if self.tool_choice:
                params["tool_choice"] = self.tool_choice
            if self.tool_prompt_format:
                params["tool_prompt_format"] = self.tool_prompt_format
            self.tool_config = ToolConfig(**params)


@json_schema_type
class AgentConfig(AgentConfigCommon):
    """Configuration for creating a new agent.
    
    This class extends AgentConfigCommon with additional parameters specific
    to agent creation.
    
    Attributes:
        model: The model to use for the agent
        instructions: Instructions that define the agent's behavior
        enable_session_persistence: Whether to persist the session state
        response_format: Optional format for the agent's responses
    """
    model: str
    instructions: str
    enable_session_persistence: Optional[bool] = False
    response_format: Optional[Any] = None  # ResponseFormat


class AgentConfigOverridablePerTurn(AgentConfigCommon):
    """Configuration parameters that can be overridden per turn.
    
    This class extends AgentConfigCommon with parameters that can be
    overridden for individual turns in a session.
    
    Attributes:
        instructions: Optional instructions that override the agent's default instructions
    """
    instructions: Optional[str] = None


class AgentTurnResponseEventType(Enum):
    """Enumeration of event types for agent turn responses.
    
    These event types represent different stages and actions in the agent turn
    response lifecycle.
    
    Attributes:
        step_start: Event indicating the start of a step
        step_complete: Event indicating the completion of a step
        step_progress: Event indicating progress within a step
        turn_start: Event indicating the start of a turn
        turn_complete: Event indicating the completion of a turn
        turn_awaiting_input: Event indicating the turn is waiting for input
    """
    step_start = "step_start"
    step_complete = "step_complete"
    step_progress = "step_progress"

    turn_start = "turn_start"
    turn_complete = "turn_complete"
    turn_awaiting_input = "turn_awaiting_input"


@json_schema_type
class AgentTurnResponseStepStartPayload(BaseModel):
    """Payload for the step_start event in agent turn responses.
    
    This class represents the data sent when a step starts during an agent turn.
    
    Attributes:
        event_type: The type of event, always "step_start" for this class
        step_type: Type of the step being started
        step_id: Unique identifier for the step
        metadata: Optional metadata associated with the step
    """
    event_type: Literal["step_start"] = AgentTurnResponseEventType.step_start.value
    step_type: StepType
    step_id: str
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)


@json_schema_type
class AgentTurnResponseStepCompletePayload(BaseModel):
    """Payload for the step_complete event in agent turn responses.
    
    This class represents the data sent when a step completes during an agent turn.
    
    Attributes:
        event_type: The type of event, always "step_complete" for this class
        step_type: Type of the step that completed
        step_id: Unique identifier for the step
        step_details: Detailed information about the completed step
    """
    event_type: Literal["step_complete"] = AgentTurnResponseEventType.step_complete.value
    step_type: StepType
    step_id: str
    step_details: Step


@json_schema_type
class AgentTurnResponseStepProgressPayload(BaseModel):
    """Payload for the step_progress event in agent turn responses.
    
    This class represents the data sent when progress is made within a step
    during an agent turn.
    
    Attributes:
        event_type: The type of event, always "step_progress" for this class
        step_type: Type of the step in progress
        step_id: Unique identifier for the step
        delta: Content delta representing the incremental progress
    """
    model_config = ConfigDict(protected_namespaces=())

    event_type: Literal["step_progress"] = AgentTurnResponseEventType.step_progress.value
    step_type: StepType
    step_id: str

    delta: Any  # ContentDelta


@json_schema_type
class AgentTurnResponseTurnStartPayload(BaseModel):
    """Payload for the turn_start event in agent turn responses.
    
    This class represents the data sent when a turn starts.
    
    Attributes:
        event_type: The type of event, always "turn_start" for this class
        turn_id: Unique identifier for the turn
    """
    event_type: Literal["turn_start"] = AgentTurnResponseEventType.turn_start.value
    turn_id: str


@json_schema_type
class AgentTurnResponseTurnCompletePayload(BaseModel):
    """Payload for the turn_complete event in agent turn responses.
    
    This class represents the data sent when a turn completes.
    
    Attributes:
        event_type: The type of event, always "turn_complete" for this class
        turn: The completed turn object with all details
    """
    event_type: Literal["turn_complete"] = AgentTurnResponseEventType.turn_complete.value
    turn: Turn


@json_schema_type
class AgentTurnResponseTurnAwaitingInputPayload(BaseModel):
    """Payload for the turn_awaiting_input event in agent turn responses.
    
    This class represents the data sent when a turn is waiting for input,
    typically when the agent needs additional information to proceed.
    
    Attributes:
        event_type: The type of event, always "turn_awaiting_input" for this class
        turn: The turn object that is awaiting input
    """
    event_type: Literal["turn_awaiting_input"] = (
        AgentTurnResponseEventType.turn_awaiting_input.value
    )
    turn: Turn


AgentTurnResponseEventPayload = register_schema(
    Annotated[
        Union[
            AgentTurnResponseStepStartPayload,
            AgentTurnResponseStepProgressPayload,
            AgentTurnResponseStepCompletePayload,
            AgentTurnResponseTurnStartPayload,
            AgentTurnResponseTurnCompletePayload,
            AgentTurnResponseTurnAwaitingInputPayload,
        ],
        Field(discriminator="event_type"),
    ],
    name="AgentTurnResponseEventPayload",
)


@json_schema_type
class AgentTurnResponseEvent(BaseModel):
    """Event for agent turn responses.
    
    This class represents an event that occurs during an agent turn,
    containing a payload with the specific event details.
    
    Attributes:
        payload: The payload containing the specific event details
    """
    payload: Any  # AgentTurnResponseEventPayload


@json_schema_type
class AgentCreateResponse(BaseModel):
    """Response for agent creation.
    
    This class represents the response returned when a new agent is created.
    
    Attributes:
        agent_id: Unique identifier for the newly created agent
    """
    agent_id: str


@json_schema_type
class AgentSessionCreateResponse(BaseModel):
    """Response for agent session creation.
    
    This class represents the response returned when a new agent session is created.
    
    Attributes:
        session_id: Unique identifier for the newly created session
    """
    session_id: str


@json_schema_type
class AgentTurnCreateRequest(AgentConfigOverridablePerTurn):
    """Request for creating a new agent turn.
    
    This class represents the request to create a new turn in an agent session,
    including the messages to process and optional configuration overrides.
    
    Attributes:
        agent_id: Identifier for the agent to use
        session_id: Identifier for the session to create the turn in
        messages: List of messages to process in this turn
        documents: Optional list of documents to provide to the agent
        toolgroups: Optional list of tool groups to override the agent's default tools
        stream: Whether to stream the response
        tool_config: Optional tool configuration to override the agent's default
        allow_turn_resume: Whether to allow resuming this turn (temporary flag)
    """
    agent_id: str
    session_id: str

    # TODO: figure out how we can simplify this and make why
    # ToolResponseMessage needs to be here (it is function call
    # execution from outside the system)
    messages: List[
        Union[
            UserMessage,
            ToolResponseMessage,
        ]
    ]

    documents: Optional[List[Any]] = None  # List[Document]
    toolgroups: Optional[List[Any]] = None  # List[AgentToolGroup]

    stream: Optional[bool] = False
    tool_config: Optional[ToolConfig] = None

    # TODO (xiyan): temporary flag, will remove for 0.1.5
    allow_turn_resume: Optional[bool] = False


@json_schema_type
class AgentTurnResumeRequest(BaseModel):
    """Request for resuming an agent turn.
    
    This class represents the request to resume a turn that was awaiting input,
    typically after client-side tool calls have been executed.
    
    Attributes:
        agent_id: Identifier for the agent
        session_id: Identifier for the session
        turn_id: Identifier for the turn to resume
        tool_responses: List of tool response messages to provide to the agent
        stream: Whether to stream the response
    """
    agent_id: str
    session_id: str
    turn_id: str
    tool_responses: List[ToolResponseMessage]
    stream: Optional[bool] = False


@json_schema_type
class AgentTurnResponseStreamChunk(BaseModel):
    """Streamed agent turn completion response.
    
    This class represents a chunk of a streamed response for an agent turn,
    containing an event with information about the turn's progress.
    
    Attributes:
        event: The event contained in this stream chunk
    """

    event: AgentTurnResponseEvent


@json_schema_type
class AgentStepResponse(BaseModel):
    """Response for retrieving an agent step.
    
    This class represents the response returned when retrieving a specific
    step from an agent turn.
    
    Attributes:
        step: The step object with all details
    """
    step: Step


@runtime_checkable
@trace_protocol
class Agents(Protocol):
    """Agents API for creating and interacting with agentic systems.

    Main functionalities provided by this API:
    - Create agents with specific instructions and ability to use tools.
    - Interactions with agents are grouped into sessions ("threads"), and each interaction is called a "turn".
    - Agents can be provided with various tools (see the ToolGroups and ToolRuntime APIs for more details).
    - Agents can be provided with various shields (see the Safety API for more details).
    - Agents can also use Memory to retrieve information from knowledge bases. See the RAG Tool and Vector IO APIs for more details.
    
    This API serves as the primary interface for creating and managing agents,
    their sessions, turns, and steps in the Llama Stack framework.
    """

    @webmethod(route="/agents", method="POST")
    async def create_agent(
        self,
        agent_config: AgentConfig,
    ) -> AgentCreateResponse:
        """Create a new agent with the specified configuration.
        
        This method creates a new agent with the provided configuration,
        including model, instructions, and optional tools.
        
        Args:
            agent_config: Configuration for the new agent
            
        Returns:
            Response containing the ID of the newly created agent
        """
        ...

    @webmethod(route="/agents/{agent_id}/session/{session_id}/turn", method="POST")
    async def create_agent_turn(
        self,
        agent_id: str,
        session_id: str,
        messages: List[
            Union[
                UserMessage,
                ToolResponseMessage,
            ]
        ],
        stream: Optional[bool] = False,
        documents: Optional[List[Document]] = None,
        toolgroups: Optional[List[Any]] = None,  # List[AgentToolGroup]
        tool_config: Optional[ToolConfig] = None,
        allow_turn_resume: Optional[bool] = False,
    ) -> Union[Turn, AsyncIterator[AgentTurnResponseStreamChunk]]:
        """Create a new turn in an agent session.
        
        This method creates a new turn in the specified agent session,
        processing the provided messages and returning the agent's response.
        
        Args:
            agent_id: Identifier for the agent
            session_id: Identifier for the session
            messages: List of messages to process in this turn
            stream: Whether to stream the response
            documents: Optional list of documents to provide to the agent
            toolgroups: Optional list of tool groups to override the agent's default tools
            tool_config: Optional tool configuration to override the agent's default
            allow_turn_resume: Whether to allow resuming this turn
            
        Returns:
            Either a complete Turn object or an AsyncIterator of stream chunks
        """
        ...

    @webmethod(
        route="/agents/{agent_id}/session/{session_id}/turn/{turn_id}/resume",
        method="POST",
    )
    async def resume_agent_turn(
        self,
        agent_id: str,
        session_id: str,
        turn_id: str,
        tool_responses: List[ToolResponseMessage],
        stream: Optional[bool] = False,
    ) -> Union[Turn, AsyncIterator[AgentTurnResponseStreamChunk]]:
        """Resume an agent turn with executed tool call responses.
        
        When a Turn has the status `awaiting_input` due to pending input from client side 
        tool calls, this endpoint can be used to submit the outputs from the tool calls 
        once they are ready.
        
        Args:
            agent_id: The ID of the agent to resume
            session_id: The ID of the session to resume
            turn_id: The ID of the turn to resume
            tool_responses: The tool call responses to resume the turn with
            stream: Whether to stream the response
            
        Returns:
            A Turn object if stream is False, otherwise an AsyncIterator of 
            AgentTurnResponseStreamChunk objects
        """
        ...

    @webmethod(
        route="/agents/{agent_id}/session/{session_id}/turn/{turn_id}",
        method="GET",
    )
    async def get_agents_turn(
        self,
        agent_id: str,
        session_id: str,
        turn_id: str,
    ) -> Turn:
        """Retrieve a specific turn from an agent session.
        
        This method retrieves the details of a specific turn in an agent session,
        including all steps and messages.
        
        Args:
            agent_id: Identifier for the agent
            session_id: Identifier for the session
            turn_id: Identifier for the turn to retrieve
            
        Returns:
            The complete Turn object with all details
        """
        ...

    @webmethod(
        route="/agents/{agent_id}/session/{session_id}/turn/{turn_id}/step/{step_id}",
        method="GET",
    )
    async def get_agents_step(
        self,
        agent_id: str,
        session_id: str,
        turn_id: str,
        step_id: str,
    ) -> AgentStepResponse:
        """Retrieve a specific step from an agent turn.
        
        This method retrieves the details of a specific step within a turn,
        such as an inference step, tool execution step, etc.
        
        Args:
            agent_id: Identifier for the agent
            session_id: Identifier for the session
            turn_id: Identifier for the turn
            step_id: Identifier for the step to retrieve
            
        Returns:
            Response containing the step details
        """
        ...

    @webmethod(route="/agents/{agent_id}/session", method="POST")
    async def create_agent_session(
        self,
        agent_id: str,
        session_name: str,
    ) -> AgentSessionCreateResponse:
        """Create a new session for an agent.
        
        This method creates a new session for the specified agent,
        which can be used to group related interactions.
        
        Args:
            agent_id: Identifier for the agent
            session_name: Name for the new session
            
        Returns:
            Response containing the ID of the newly created session
        """
        ...

    @webmethod(route="/agents/{agent_id}/session/{session_id}", method="GET")
    async def get_agents_session(
        self,
        session_id: str,
        agent_id: str,
        turn_ids: Optional[List[str]] = None,
    ) -> Session:
        """Retrieve a specific agent session.
        
        This method retrieves the details of a specific agent session,
        optionally including only the specified turns.
        
        Args:
            session_id: Identifier for the session to retrieve
            agent_id: Identifier for the agent
            turn_ids: Optional list of turn IDs to include in the response
            
        Returns:
            The complete Session object with requested turns
        """
        ...

    @webmethod(route="/agents/{agent_id}/session/{session_id}", method="DELETE")
    async def delete_agents_session(
        self,
        session_id: str,
        agent_id: str,
    ) -> None:
        """Delete a specific agent session.
        
        This method permanently deletes an agent session and all its associated turns and steps.
        
        Args:
            session_id: Identifier for the session to delete
            agent_id: Identifier for the agent
            
        Returns:
            None
        """
        ...

    @webmethod(route="/agents/{agent_id}", method="DELETE")
    async def delete_agent(
        self,
        agent_id: str,
    ) -> None:
        """Delete a specific agent.
        
        This method permanently deletes an agent and all its associated sessions, turns, and steps.
        
        Args:
            agent_id: Identifier for the agent to delete
            
        Returns:
            None
        """
        ...
